<?php

namespace UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function showAllUsers() {
        
        $users = $this->getDoctrine()
                ->getRepository('UserBundle:User')
                ->findAll();
     

        if (!$users) {
            throw $this->createNotFoundException(
                    'No users found' 
            );
        }

        return new Response($users);
        
    }
}
